# Generated by Django 5.0.7 on 2024-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('release_date', models.DateTimeField()),
                ('toy_category', models.CharField(default='Action Figure', max_length=200)),
                ('was_included_in_home', models.BooleanField(default=False)),
                ('createad', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
